name: flutter_pusher
description: A Flutter plugin to listen to events sent through pusher. Wraps the native Java and Swift libraries.
version: 2.0.0-nullsafety.0
author: Indoor Solutions <ninjas@indoor.solutions>
homepage: https://github.com/ninjasolutions/flutter_pusher

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  json_annotation: ^4.0.1
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^1.5.2
  json_serializable: ^4.1.0
  flutter_test:
    sdk: flutter

flutter:
  # This section identifies this Flutter project as a plugin project.
  # The androidPackage and pluginClass identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    androidPackage: com.ninjasolutions.pusher
    pluginClass: PusherPlugin
